### ISSUE TITLE
Frontend - Accessibilité et Checklist Pidila

### ISSUE THREAD

**Issue by david-bretaud-dev** [pims-online/pims-frontend#4]
# Accessibilité et Checklist Pidila

## Usage

L'accessibilité désigne les éléments mis en place pour rendre le site le plus accessible possible, c'est-à-dire lisible par les daltoniens, les mal-voyants, utilisable seulement à l'aide du clavier, etc ...

Dans le pied de page (footer) de tout site gouvernementaux, on trouve un lien vers une page contenant les informations sur l'accessibilité du site. Celle-ci peut être "non conforme", "partiellement conforme" ou "totalement conforme" (exemple du [DSFR](https://www.systeme-de-design.gouv.fr/)).

Pour déterminer la conformité, un audit doit être réalisé. Celui-ci se base sur la [Checklist pidila](https://design.numerique.gouv.fr/outils/checklist-pidila/). C'est une liste très complète abordant divers thème.
Divers outils permettent de mieux l'appréhender : <https://design.numerique.gouv.fr/outils/>.

## POC

La page d'accessibilité du POC se trouve ici : <https://pims-frontend.vercel.app/accessibilite>.
Comme on peut le lire sur la page, il n'y a pas d'audit qui a été réalisé.
De même en interne, la checklist n'a pas été regardée dans son ensemble. Ainsi, des points peuvent être manquants.

## Gouvernement

- [ ] Réaliser un audit interne de la checklist, pour cerner les points sur lesquels il faudrait travailler.
- [ ] Faire les modifications nécessaires pour compléter un maximum d'items de la Checklist Pidila (ou du moins créer des issues pour que ces modifications soient prévues).
- [ ] Faire un Audit du site, et mettre à jour la déclaration d'accessibilité. Il est possible de se baser sur ce générateur pour trouver les bons verbatim : <https://betagouv.github.io/a11y-generateur-declaration/#create>.
